version: '3'

services:

  nginx:
    build:
      context: ./nginx 
      dockerfile: Dockerfile 
    image: eddyajunior/nginx-desafio:prod
    container_name: nginx-desafio 
    networks:
      - desafio-net
    volumes:
      - ./nginx:/usr/src/app
    tty: true 
    ports:
      - "8080:80"    
    depends_on:
      - db

  app:  
    build:
      context: ./node 
      dockerfile: Dockerfile 
    image: eddyajunior/node-desafio:prod
    container_name: node-desafio 
    entrypoint: dockerize -wait tcp://db:3306 -timeout 40s docker-entrypoint.sh node index.js
    networks:
      - desafio-net  
    volumes:
      - ./node:/usr/src/app
      - /usr/src/app/node_modules
    tty: true 
    ports:
      - "3000:3000"    
    depends_on:
      - db


  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: mysql-desafio
    restart: always
    tty: true 
    volumes:
      - ./mysql-data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=docker-db-desafio
      - MYSQL_ROOT_PASSWORD=pwd-desafio
    networks:
      - desafio-net

networks:
  desafio-net:
    driver: bridge      